### ISSUE TITLE
current version already exists

### ISSUE THREAD

**Issue by asdfCYBER** [dkavolis/Ferram-Aerospace-Research#1]
version 0.15.9.2 already exists: https://github.com/asdfCYBER/Ferram-Aerospace-Research/releases/tag/v0.15.9.2_ferram4
To avoid confusion and github fork incompatibilities, please consider forking the latest version in the future.

**Comment by dkavolis** [comment]
Thanks, will fork the latest version next time, in the mean time I have incremented the version number to 0.15.9.5.

c6661d96b9f58ccc0029cde7d54ae8b4fbe1dbe7
[Releases](https://github.com/dkavolis/Ferram-Aerospace-Research/releases)

**Comment by asdfCYBER** [comment]
thanks :)

**Comment by asdfCYBER** [comment]
(note: you forgot the links in the forum post - they're broken now :P)

**Comment by dkavolis** [comment]
Sorry, updated the post.

**Comment by asdfCYBER** [comment]
wow, response time +1
