### ISSUE TITLE
Potential typo

### ISSUE THREAD

**Issue by MacKenzieHnC** [dkavolis/Ferram-Aerospace-Research#117]
Line 922 in Ferram-Aerospace-Research/GameData/FerramAerospaceResearch/FerramAerospaceResearch.cfg reads 
```@PART[*]:HAS[#module[ControlSurface],@MODULE[FARControllableSurface]]:FOR[FerramAerospaceResearch]``` 
when I think it is supposed to be
```@PART[*]:HAS[@MODULE[ModuleControlSurface],@MODULE[FARControllableSurface]]:FOR[FerramAerospaceResearch]```

I'm new here, so I could be way wrong though.

**Comment by dkavolis** [comment]
There's already
https://github.com/dkavolis/Ferram-Aerospace-Research/blob/135bb128f58e53f21952957e9ee44b9222daf714/GameData/FerramAerospaceResearch/FerramAerospaceResearch.cfg#L918-L921

I think `ControlSurface` is a legacy remain
