### ISSUE TITLE
Assembly Building Calculations Above Threshold Mach Throw NullReferenceException

### ISSUE THREAD

**Issue by girbrother2** [dkavolis/Ferram-Aerospace-Research#118]
​
Running FAR 0.16.0.2, performing calculations in the assembly buildings with Mach greater than a certain threshold fails and gives an exception.  Relevant part of log attached.
[MachSweepFARException.txt](https://github.com/dkavolis/Ferram-Aerospace-Research/files/6600917/MachSweepFARException.txt)

This occurs with all parts with FARWingAerodynamicModel.
​

**Comment by girbrother2** [comment]
This was a part issue, not due to FAR.

**Comment by dkavolis** [comment]
Should be fixed in e087d95
