### ISSUE TITLE
Make FAR aerodynamic presets MM-configurable

### ISSUE THREAD

**Issue by siimav** [dkavolis/Ferram-Aerospace-Research#130]
RO/RP-1 needs a way to configure what preset or values FAR applies by-default to new careers. You mentioned that in that case it might make more sense to load the profiles themselves from ConfigNodes instead of being hardcoded.
Link to previous discussion: https://discord.com/channels/319857228905447436/512556346869284864/918188039472304178

**Comment by dkavolis** [comment]
See [FARDifficultyPresets.cfg](https://github.com/dkavolis/Ferram-Aerospace-Research/blob/master/GameData/FerramAerospaceResearch/FARDifficultyPresets.cfg), currently using index to select preset at the start of a new game but I can add selection by name if needed.
