### ISSUE TITLE
Possibility to use Ferram as a flight model injector 

### ISSUE THREAD

**Issue by giuliodondi** [dkavolis/Ferram-Aerospace-Research#135]
This is not really an issue nor a feature request. 
Like the title suggests, I've been wondering if it is at all possible to bypass all the Ferram calculations/voxelisation if we already have all the data for Cl-Cd curves versus Mach and AoA.

The in-game application would be to re-create realistic Space Shuttle behaviour in Realism Overhaul.
Currently the Shuttle under-performs at high Mach number, with the in-game editor I see a L/D barely over 0.5 at 35° M20 while it should be at least 1 according to data I've collected. This results in a lot less reentry crossrange than advertised.
There are 1000+ pages documents with tables upon tables of data that would overcome these issues.

I'm imagining some dll that provides a method to disable FAR computations for the current part (to be used on every part of the craft) and another that injects the flight model, to be applied only to one part (such as the main fuselage).
Is there infrastructure inside Ferram to make this happen?

**Comment by dkavolis** [comment]
Check https://github.com/dkavolis/Ferram-Aerospace-Research/commit/476e99b84a5bea015de9a71555988234d81dff85

It doesn't disable FAR force calculations but they can be modified or overridden.
