### ISSUE TITLE
Parachutes are not reinstatiated when using KCT

### ISSUE THREAD

**Issue by Strych74** [dkavolis/Ferram-Aerospace-Research#137]
I've raised this issue with LGG who's now looking after KCT.  Since FAR patches all the parachute modules with it's own RealChuteFAR module, this appears to break the ability of KCT to "reset" the parachute when it is recovered via KCT.  Literally all parachutes on the vessel need to be manually replaced with new parts - there's no impact on the construction cost or time for the vessel, but you can imagine that this can get rather tiresome when there are several parachutes on the vessel, particularly if they are specifically configured (altitudes/pressure deployments etc.).

This behaviour can be reproduced when using a clean install with only KCT and FAR installed.

**Comment by dkavolis** [comment]
Looks like KCT needs a template for `RealChuteFAR`, similar to https://github.com/linuxgurugamer/KCT/blob/ef5b5c05212b2e68e8f98d66045365571e3d3f89/Kerbal_Construction_Time/KCT_BuildListVessel.cs#L460-L465

This is not something that can be fixed on FAR end as the KCT config templates file are not MM aware.
