### ISSUE TITLE
Parachutes deploy going too fast and instantly break

### ISSUE THREAD

**Issue by Krazy0** [dkavolis/Ferram-Aerospace-Research#138]
Parachutes deploy when going too fast and fail. From forum:

"Help... having a constant problem with parachutes. When reentering, they always deploy while going too fast and instantly get destroyed. I'm arming them in space like normal and they just deploy too soon. I'm using Mk16-XL and Mk25. They have default settings including "deploy when safe" but they are not doing so. I just tried to land on Laythe and the drogues deployed at about 1200 m/s at 22 km up. The mains deployed at over 1100 m/s." -Krazy1

Similar results on Kerbin.

**Comment by dkavolis** [comment]
The behaviour is the same as RealChute, FAR doesn't expose an option to `deploy when safe`. Instead, adjust deployment altitude and pressure or deploy manually when the stack icons are no longer red.
