### ISSUE TITLE
[VehicleAerodynamics] Dictionary<Part, PartTransformInfo> _partWorldToLocalMatrixDict> thown away

### ISSUE THREAD

**Issue by GER-Space** [dkavolis/Ferram-Aerospace-Research#14]
The dictionary is cleared for each time its accesed, also converting a part to a key value for a dictionanry is very slow. 
part.persistentId would be faster to use. (its unique as long the part exists)

**Comment by dkavolis** [comment]
Thanks for this, I'll also check other dicts for similar behavior.

**Comment by dkavolis** [comment]
I don't think this is actually a problem for optimisation. The dictionary is only used for voxelization which:
1. Is only done on part and vessel hierarchy changes
1. Voxelization usually takes O(10^2) ms to complete so saving fraction of a millisecond is negligible
1. The hash code is the object reference from [RuntimeHelpers.GetHashCode(Object)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.runtimehelpers.gethashcode?redirectedfrom=MSDN&view=netframework-3.5#System_Runtime_CompilerServices_RuntimeHelpers_GetHashCode_System_Object_)
