### ISSUE TITLE
FIle versioning and compatibility for RO

### ISSUE THREAD

**Issue by raidernick** [dkavolis/Ferram-Aerospace-Research#17]
It seems like we may be using this for RO soon as a replacement for the original FAR. While the latest release you have is ok for downloads on the forum it has a couple of issues I'd like to ask you to fix otherwise we will have to make our own RO repo for FAR releases instead of using this. 

The first issue is that you are not updating the far dll verison number it is still on 0.15.9.1 for all of your releases.

The second issue is that RO uses CKAN. We are catching up on our releases for KSP currently and are doing a ksp 1.4.5 release then moving straight to 1.6.x. You HAVE a 1.4.5 release posted as a google drive link inside a 1.5 release. While this is ok for a forum release, it will not work with RO/RSS on CKAN. I would ask that you fix the versioning of your files, make an official 1.4.5 release, then remake a new 1.5.x release with the proper version numbers and then move to 1.6.x...etc...

You can easily accomplish this be changing the epoch in netkan.

**Comment by dkavolis** [comment]
Regarding dll version, I forgot to update it but will do on all other releases. It also looks like Squad has done a great job at mod compatibility in the last few KSP versions so I can do one release for KSP 1.4-1.6 unless there are bugs I haven't found yet.

**Comment by raidernick** [comment]
Thank you, this is one of 3 mods that are holding the 1.4.5 release of RO up. I have control over the other 2 and those will be done soon, this is the final one. I would really appreciate a release that covers all of those versions so I can finally move on with RO/RSS and get it up to date on time from now on.

**Comment by dkavolis** [comment]
Published a release for KSP 1.4-1.6, let me know of any issues. The MM fix is included which I had fixed earlier.

**Comment by dkavolis** [comment]
I tried both CKAN version and dropping FAR into GameData on KSP 1.4.5 and had no issues with MFI. Can you provide logs?

**Comment by raidernick** [comment]
It works fine on ckan because ckan will install MFI separately and only the version that is compatible with 1.4.5. The version in your release is marked as 1.5 compatible only, so even if it worked it will complain in both 1.4 and 1.6 that it's incompatible. I have no logs, my game hasn't generated a log file since before 1.2.2. They made some change to the game then and it stopped producing the proper log files.

Dropping FAR in works fine, as long as your don't have kopernicus. It's kopernicus that breaks. If you use the MFI that comes with the 1.4.5 version of kopernicus it works fine, if you overwrite it with the version you have in FAR everything breaks. Kopernicus is locked to the MFI version released with it is the issue.

**Comment by dkavolis** [comment]
I can add a note for Kopernicus users that they should use MFI bundled with it since Kopernicus is locked to a specific MFI version and only manual installations are affected. Otherwise, what do you suggest on how to proceed?

**Comment by raidernick** [comment]
I would've personally separated the 1.4.5 and 1.5-1.6 releases into 2 separate ones, but it's too late for that now. Not sure what to do really.
