### ISSUE TITLE
Rodhern's update 3.

### ISSUE THREAD

**Issue by Rodhern** [dkavolis/Ferram-Aerospace-Research#4]
A short silly question: I have some minor updates and tweaks for the KSP 1.3.1 version of FAR (I don't play 1.5.1) over [here](https://github.com/Rodhern/Ferram-Aerospace-Research/tree/v0.15.9.1_Rodhern_update_3). Are you interested in a naive merge pull request?
(If so, I will try to remember it if I get free time later on).

**Comment by dkavolis** [comment]
Sure, go ahead, pull requests are welcome. Just include a description of the changes made and I'll have a look.
