### ISSUE TITLE
Compatibility Problem of B9 Procedural Wings of latest version in 1.6

### ISSUE THREAD

**Issue by tetraflon** [dkavolis/Ferram-Aerospace-Research#45]
If the procedural wing area is set large enough i.e. 8x8m^2 for Type A Wing, lift will not be generated.
Reproduce:
get fresh install KSP 1.6.1
manually install B9PW(0.90), MFI(1.26), FAR(0.15.10.0), MM(4.0.2)
start game 
go to SPH editor mode and built a plane with large b9pw panels.
go to flight mode and test, no lift generated on main wing, no problem for small surfaces.
log provided by player: [KSP.log](https://drive.google.com/open?id=1UwZ8tgu5MEiYMAcnmbb1_BuTuln9pmGp)

**Comment by siimav** [comment]
Yep, can confirm that the latest FAR has issues with B9 proc wings on KSP 1.6.1.

**Comment by dkavolis** [comment]
I suspect what's going wrong - even though `forceUseMeshes` is true in the config, somehow FAR still uses colliders for voxelization. Hopefully won't take long to fix.

**Comment by dkavolis** [comment]
So somehow on scene load `forceUseMeshes` gets reset to `false` even though it has `[SerializeField]` attribute...
