### ISSUE TITLE
Request: Make the stock EVA/Kerbal parachute FAR compatible.

### ISSUE THREAD

**Issue by Galenmacil** [dkavolis/Ferram-Aerospace-Research#62]
I prefer to categorize this as "request" rather than "issue" because all stock parachute need special handing to work with FAR.

**Comment by dkavolis** [comment]
The full RealChutes mod does not have special handling for EVA chutes so there is not much I can do.

**Comment by Galenmacil** [comment]
OK. There is this mod managed by linuxgurugamer (https://github.com/linuxgurugamer/EVAParachutesAndEjectionSeats) that does handle FAR... I am using it right now. I just thought I'd ask for that feature. Thanks for maintaining FAR by the way, best aerodynamic mod of any simulator I know off.

**Comment by dkavolis** [comment]
The stock EVA chutes are parafoils so properly simulating those might be difficult. In addition, kerbals also use stock aerodynamics and their voxelization is a box.

Anyway, the cases where EVA chutes are going to be used are not critical so there is not much incentive in making them slightly more accurate.

**Comment by Galenmacil** [comment]
Humm. With FAR installed, currently, the stock EVA chute simply do not work: They have no drag at all...

**Comment by dkavolis** [comment]
Do they have lift, only no drag?

**Comment by dkavolis** [comment]
> Humm. With FAR installed, currently, the stock EVA chute simply do not work: They have no drag at all...

I don't think this is FAR issue. FAR doesn't remove ModuleLiftingSurface from kerbals, neither replace EVA chute module. It should work as in stock with additional drag added from voxelized kerbal box.

**Comment by Galenmacil** [comment]
You are right: This is not a FAR issue. I tested it out with only FAR installed and nothing else. The chute worked. I will have to do more testing and find out why it doesn't in my Career game. You can close this issue...
