### ISSUE TITLE
Log spam and very low fps in VAB/SPH when RF UI is open

### ISSUE THREAD

**Issue by Gordon-Dry** [dkavolis/Ferram-Aerospace-Research#67]
When the tank UI of MFT/RF is open in VAB/SPH, this is spammed to the log and the reaction times are disgustingly low:
```
[FAR v0.15.10.1] Updating CRAFTNAME *
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

```
* obvious, I edited that, enter name of actual craft there

**Comment by dkavolis** [comment]
Can you give the full log?

**Comment by Gordon-Dry** [comment]
https://www.dropbox.com/s/w24adhkpn289sp0/output_log.txt%20and%20stuff%202019-06-07-01.zip?dl=1

**Comment by dkavolis** [comment]
Can't reproduce it on my setup. RF UI lags a lot though but it's not due to FAR.

**Comment by Gordon-Dry** [comment]
Ok. 
It's just that the FAR log spamming only occurs when the RF UI is open.

**Comment by dkavolis** [comment]
Something is probably firing editor events, which FAR subscribes to:
```csharp
GameEvents.onEditorVariantApplied
GameEvents.onEditorPartEvent
GameEvents.onEditorUndo
GameEvents.onEditorRedo
GameEvents.onEditorShipModified
GameEvents.onEditorLoad
```

**Comment by Gordon-Dry** [comment]
This (yes for real) exiting issue seems to be fixed with
https://github.com/NathanKell/ModularFuelSystem/pull/222

Fix needs testing.
