### ISSUE TITLE
NRE in editor when placing specific engine.

### ISSUE THREAD

**Issue by Galenmacil** [dkavolis/Ferram-Aerospace-Research#72]
I could not manage to reproduce the problem reliably. 

> 
> [LOG 01:31:10.355] [FAR v0.15.11.0] Voxelization Time (ms): 133
> [LOG 01:31:11.123] cyclone added to ship - part count: 2
> [LOG 01:31:11.166] [FAR v0.15.11.0] Overall bounds error in "Cyclone" VTOL Lifter Section 0 meshes
> [LOG 01:31:11.190] [FAR v0.15.11.0] Overall bounds error in "Cyclone" VTOL Lifter Section 0 meshes
> [LOG 01:31:11.825] [FAR v0.15.11.0] Updating Untitled Space Craft
> [LOG 01:31:11.826] [FAR v0.15.11.0] Overall bounds error in "Cyclone" VTOL Lifter Section 0 meshes
> [ERR 01:31:11.856] [FAR v0.15.11.0] Logged exception:
> 
> [EXC 01:31:11.857] KeyNotFoundException: The given key was not present in the dictionary.
> 	System.Collections.Generic.Dictionary`2[Part,FerramAerospaceResearch.FARPartGeometry.PartTransformInfo].get_Item (.Part key)
> 	FerramAerospaceResearch.FARAeroComponents.FARAeroSection.UpdateAeroSection (Single potentialFlowNormalForce, Single viscCrossflowDrag, Single diameter, Single flatnessRatio, Single hypersonicMomentForward, Single hypersonicMomentBackward, Vector3 centroidWorldSpace, Vector3 xRefVectorWorldSpace, Vector3 nRefVectorWorldSpace, Matrix4x4 vesselToWorldMatrix, Vector3 vehicleMainAxis, System.Collections.Generic.List`1 moduleList, System.Collections.Generic.List`1 dragFactor, System.Collections.Generic.Dictionary`2 partWorldToLocalMatrixDict)
> 	FerramAerospaceResearch.FARAeroComponents.VehicleAerodynamics.CalculateVesselAeroProperties ()
> 	FerramAerospaceResearch.FARAeroComponents.VehicleAerodynamics.CreateVoxel ()
> 	UnityEngine.Debug:LogException(Exception)
> 	FerramAerospaceResearch.FARUtils.FARLogger:Exception(Exception)
> 	FerramAerospaceResearch.FARThreading.ThreadSafeDebugLogger:Update()

The engine in question is part of the Quiztech Aero mod. Note that it was working just fine in the previous FAR version... Also, the FAR calculator window can't return any stability numbers or mach information when this happen.

[KSP.log](https://github.com/dkavolis/Ferram-Aerospace-Research/files/3316542/KSP.log)

**Comment by dkavolis** [comment]
Can you provide MM cache as well? For some reason FAR fails to find meshes for voxelization. Simulation failure is a result of that.

**Comment by Galenmacil** [comment]
Here it is, part name is "cyclone", it is a VTOL F35B style forward lifting fan:

[MM Cache.zip](https://github.com/dkavolis/Ferram-Aerospace-Research/files/3317348/MM.Cache.zip)
