### ISSUE TITLE
CSV flight data logging

### ISSUE THREAD

**Issue by KSAMissionCtrl** [dkavolis/Ferram-Aerospace-Research#83]
As requested, making an issue for an option in the Setting window to enable the data that is displayed in the Flt Data window to be logged out to a CSV file every second (or user-defined). Nothing fancy needed beyond that

Thanks for the consideration of this request

**Comment by dkavolis** [comment]
You can try out FAR from [logs](https://github.com/dkavolis/Ferram-Aerospace-Research/tree/logs) branch. Only the logs directory and filenames are configurable at the moment
https://github.com/dkavolis/Ferram-Aerospace-Research/blob/60ed0abc6e1cc9cc779d8831d73a25892a89f53c/GameData/FerramAerospaceResearch/FARConfig.cfg#L1-L19

Data logged:
https://github.com/dkavolis/Ferram-Aerospace-Research/blob/60ed0abc6e1cc9cc779d8831d73a25892a89f53c/FerramAerospaceResearch/FARGUI/FARFlightGUI/FlightDataLogger.cs#L215-L242

**Comment by KSAMissionCtrl** [comment]
w00t! I will check it as soon as I have time to get a 1.8 install up and running

**Comment by dkavolis** [comment]
Just FYI, `FARConfig` should be modified through MM as `@FARConfig[default]:FINAL{}`

**Comment by dkavolis** [comment]
I've refactored the config parser to be much more easily extendable and have no dependency on KSP assemblies for when I split off some functionality to be shared with UI module. The logging config is now a `CONFIG` node in `FARConfig` with `name = flightLog`.

**Comment by KSAMissionCtrl** [comment]
okay my 1.8.1 is finally setup. What's the status on this? Still need to grab the logs branch? I didn't see anything in the change log that said it had been merged into the main release yet

**Comment by dkavolis** [comment]
I've reworked the implementation which is cleaner and better but currently it sits on a local branch, just a few more tweaks until it's ready.

**Comment by KSAMissionCtrl** [comment]
I have a mission to fly anytime this week starting today so if you'd like testing just push what you have and I will check it out!

**Comment by dkavolis** [comment]
Try [dev branch](https://github.com/dkavolis/Ferram-Aerospace-Research/tree/dev) and [FARConfig.cfg](https://github.com/dkavolis/Ferram-Aerospace-Research/blob/dev/GameData/FerramAerospaceResearch/FARConfig.cfg) for options, works with MM. Note that there's an additional DLL now for adding and testing new features directly in Unity editor.

**Comment by KSAMissionCtrl** [comment]
nice, I was planning to fly tomorrow. Will let you know how it goes, thanks!

**Comment by KSAMissionCtrl** [comment]
great stuff, no major issues, ALL THE DATA YAY

Would it be difficult to change the log interval to ms? If not, no worries

**Comment by dkavolis** [comment]
As in ms in KSP game time? Wouldn't be too difficult, also it makes more sense than couting frames.

**Comment by dkavolis** [comment]
Done in c74e78e
