### ISSUE TITLE
FAR stutters and lags when ALG is on the craft.

### ISSUE THREAD

**Issue by Toonu** [dkavolis/Ferram-Aerospace-Research#87]
Hello, this issue occurred to me in both 1.7.3. There is periodic lag when using KerbalFoundries and FAR together and it works fine when without it. The lags occurs when using Adjustable Landing Gear from Kerbal Foundries, I have already submitted bug there but it links them to the FAR mod.

Issue in KF.
https://github.com/shadowmage45/KerbalFoundries2/issues/12

KSP.log

Without wheels
https://youtu.be/HEYlj63l3Q0

With wheels
https://youtu.be/8inkJqLAcj0

**Comment by dkavolis** [comment]
Can you also upload the craft file? It will make debugging easier.

**Comment by Toonu** [comment]
It can be replicated with any aircraft, I even tried it on your E42 that comes stock with the mod.

**Comment by dkavolis** [comment]
I'm going to need the complete list of mods, the craft file and MM cache. I tried FAR 0.15.11.2 in KSP 1.7 with ALG and did not encounter any stuttering in flight.

**Comment by Toonu** [comment]
The problem was resolved by switching to the KSP 1.8.1 it seems. Even when using KF and FAR together, it is perfectly fine. I am not sure what caused it, but it strange? Shall we close this or do you still want information so you can try to dig deeper into older FAR version?

**Comment by dkavolis** [comment]
I'm not interested in maintaining FAR for older KSP versions especially since KSP 1.8 upgraded Unity version, which comes with slightly different API, unless there's a serious bug for RO users. One of possible causes could have been a strange interaction between multiple mods, not just FAR and KF.
