### ISSUE TITLE
[1.9.9] NullPointerException when loading a craft

### ISSUE THREAD

**Issue by markusa380** [dkavolis/Ferram-Aerospace-Research#90]
Find the attached log.

Loading a craft works exactly once, then never again unless the mod is uninstalled completely.

[KSP.log](https://github.com/dkavolis/Ferram-Aerospace-Research/files/4577059/KSP.log)

**Comment by dkavolis** [comment]
Fixed in dev branch, will be in the next release

**Comment by markusa380** [comment]
Any way to use the dev version for now?

**Comment by dkavolis** [comment]
Just copy `GameData` folder from the branch into KSP folder

**Comment by markusa380** [comment]
Thanks 👍
