### ISSUE TITLE
KSP 1.8.1 - Aerodynamic issue with FAR and Principia

### ISSUE THREAD

**Issue by ArrowMaxGithub** [dkavolis/Ferram-Aerospace-Research#91]
**Mods in question:**
FAR continued - 0.15.11.4
Principia - 'Fubini' for KSP 1.8.1 and 1.9.0

**Additional mods and dependencies:**
Real Solar System - 18.0
Kopernicus Planetary System Modifier - 1.8.1.1
Module Manager - 4.1.3
Modular Flight Integrator - 1.2.7.0

**Issue:**
With both FAR continued and Principia installed, any change in flight controls will result in a short 'kick'. 
Example GIF:
![FAR and Principia](https://user-images.githubusercontent.com/60489413/81422080-c8c63480-9152-11ea-9815-46aeca3d05b8.gif)

On the same install, but without Principia, the motion is smooth.
Example GIF:
![FAR alone](https://user-images.githubusercontent.com/60489413/81422180-eb584d80-9152-11ea-9e8d-250dea0c27a1.gif)

**Steps that lead to this issue:**
1) Fresh install of KSP 1.8.1
2) CKAN install of RSS and FAR continued with all dependencies
3) Manual install of Principia
4) Flying any aircraft or rocket will show the jerky motion

**Comment by dkavolis** [comment]
This is an issue with Principia, Frenet works fine.
