### ISSUE TITLE
[KSP 1.9.1 + FAR 0.15.9.1] FAR operating on Linux with Mechjeb causes NullReferenceExceptions on part destruction

### ISSUE THREAD

**Issue by Jovus** [dkavolis/Ferram-Aerospace-Research#93]
When operating with the latest version of FAR and the latest version of Mechjeb, when parts are destroyed FAR throws NREs, causing the game to freeze for several seconds. This was experienced in Arch Linux 5.7.5 w/ 16GB RAM and an nVidia 780TI using the proprietary nvidia drivers, in case that matters.

It also happens in KSP 1.8.1 and with the release versions of MechJeb and FAR instead of the dev versions, in any combination. Without the two together, no NREs occur.

**Reproduction Steps**
1) Install FAR, ModularFlightIntegrator, ModuleManager, and Mechjeb, either manually or from CKAN.
2) Create a simple plane. Rockets also experience this, but it's easier to crash a plane in a semi-controlled manner.
2a) Alternatively, load up the craft file provided via zipfile. (It's nothing special but it works.)
3) Launch your craft and begin moving.
4) Intentionally crash a part into the ground that's not the cockpit or the control point (e.g., a wing). The cockpit or a control point might work, too.

Please let me know if you need any further information.

[KSP.log](https://github.com/dkavolis/Ferram-Aerospace-Research/files/4839229/KSP.log)

[FARTester.zip](https://github.com/dkavolis/Ferram-Aerospace-Research/files/4839279/FARTester.zip)

**Comment by WC12366** [comment]
I have the same problem on windows
