### ISSUE TITLE
Game crash when I crash a rocket

### ISSUE THREAD

**Issue by WC12366** [dkavolis/Ferram-Aerospace-Research#97]
When I crash a rocket, the game crashed without displaying a crash window
here's my [Player.log](https://github.com/dkavolis/Ferram-Aerospace-Research/files/4915992/Player.log)

**Comment by dkavolis** [comment]
The log contains no warnings/errors from FAR so I doubt the crash was its fault. Are you sure it wasn't Principia that caused the crash?

**Comment by WC12366** [comment]
OK, I updated Principia to Gallai and the problem solved
