### ISSUE TITLE
Exception when Building Fairing

### ISSUE THREAD

**Issue by link4531** [dkavolis/Ferram-Aerospace-Research#99]
Obviously, I know FAR is not currently compatible with KSP 1.10 but I am reporting this exception for developer awareness:

Steps to reproduce:
Create new ship / load ship. 
Add Fairing Part.
Right Click Fairing part > Build Fairing / Edit Fairing 
Exception occurs - with KerbalFSM.RunEvent
FAR finishes compute/update for drag area.
Fairing (obviously) doesn't get created...

[LOG 22:48:52.392] [FAR v0.15.11.4] Voxelization Time (ms): 149
[LOG 22:48:53.863] [FAR v0.15.11.4] Updating M-1
[LOG 22:48:53.952] [FAR v0.15.11.4] Voxel Element CrossSection Area: 0.000728588640733176

[LOG 22:48:53.976] [FAR v0.15.11.4] Std dev for smoothing: 3 voxel total vol: 4.91658557503578 filled vol: 1.40107079521945

[LOG 22:48:54.004] [FAR v0.15.11.4] Voxelization Time (ms): 141
[EXC 22:48:57.585] Exception: FSM Error: Cannot switch states before starting. Please call StartFSM() before running the FSM.
	KerbalFSM.RunEvent (KFSMEvent evt) (at <c168e21ec56346b082f89043e76162e1>:0)
	ModuleProceduralFairing.BuildFairing () (at <c168e21ec56346b082f89043e76162e1>:0)
	BaseEvent.Invoke () (at <c168e21ec56346b082f89043e76162e1>:0)
	UIPartActionButton.OnClick () (at <c168e21ec56346b082f89043e76162e1>:0)
	UnityEngine.Events.InvokableCall.Invoke () (at <5aeafee3fea24f37abd1315553f2cfa6>:0)
	UnityEngine.Events.UnityEvent.Invoke () (at <5aeafee3fea24f37abd1315553f2cfa6>:0)
	UnityEngine.UI.Button.Press () (at <71b90c0cb66049febf95ce5efefd552e>:0)
	UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <71b90c0cb66049febf95ce5efefd552e>:0)
	UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <71b90c0cb66049febf95ce5efefd552e>:0)
	UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <71b90c0cb66049febf95ce5efefd552e>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.EventSystems.EventSystem:Update()
[LOG 22:49:02.186] [FAR v0.15.11.4] Updating M-1

**Comment by link4531** [comment]
Hope this helps with any recompile needed for KSP 1.10. If you need more information or would like additional hunting for Exceptions for new build I would be happy to help.

**Comment by dkavolis** [comment]
Can you try [dev](dkavolis/Ferram-Aerospace-Research/tree/dev) version? I get no such errors in KSP 1.10 with only FAR installed.

**Comment by link4531** [comment]
oh man. I am DUMB..... hahaha 
Please close this issue. you are a mad genius, great work keeping  FAR alive. 
Issue is resolved by using the DEV branch 👍
